pluginManagement {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven {
            url 'https://maven.aliyun.com/repository/google'
            content {
                includeGroupByRegex 'com\\.android.*'
                includeGroupByRegex 'androidx\\..*'
            }
        }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven {
            url 'https://maven.aliyun.com/repository/google'
            content {
                includeGroupByRegex 'com\\.android.*'
                includeGroupByRegex 'androidx\\..*'
            }
        }
        google()
        mavenCentral()
    }
}

rootProject.name = "SGPlayKeeper"
include ':app'
